[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
   " Plugin key-m"appings.
   " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
   imap <C-k>     <Plug>(neosnippet_expand_or_jump)
   smap <C-k>     <Plug>(neosnippet_expand_or_jump)
   xmap <C-k>     <Plug>(neosnippet_expand_target)

   " SuperTab like snippets behavior.
   " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
   "imap <expr><TAB>
   " \ pumvisible() ? "\<C-n>" :
   " \ neosnippet#expandable_or_jumpable() ?
   " \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
   smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
   \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

   " For conceal markers.
   if has('conceal')
       set conceallevel=2 concealcursor=niv
   endif
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
hook_source = '''
  set completeopt=menuone,noinsert
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#lauto_complete_delay = 0
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
