# dein_lazy.toml

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['neosnippet-snippets', 'context_filetype.vim']
# on_event = 'InsertCharPre'
# on_ft = 'snippet'
# hook_source = '''
#    " Plugin key-m"appings.
#    " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
#    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
#    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
#    xmap <C-k>     <Plug>(neosnippet_expand_target)
#
#    " For conceal markers.
#    if has('conceal')
#        set conceallevel=2 concealcursor=niv
#    endif
# '''

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# depends = ['neosnippet-snippets', 'context_filetype.vim']
# on_event = 'InsertEnter'
# hook_source = '''
#   set completeopt=menuone,noinsert
#   let g:deoplete#enable_at_startup = 1
#   let g:deoplete#lauto_complete_delay = 0
#   inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
#   inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
# '''

# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'
# depends = ['deoplete.nvim']
# on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = [
  'vim-devicons',
  'defx-icons',
  'defx-git',
]
hook_add = '''
  nnoremap <silent> <Leader>f :<C-u> Defx <CR>
'''
hook_post_source = '''
  source ~/.vim/rc/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 1
'''
on_ft = 'rust'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
