# dein.vim

[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  syntax enable
  set background=dark
  set t_Co=256
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'cespare/vim-toml'

# formatter
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'
repo = 'neoclide/coc.nvim'

# incremental search
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

# markdown preview
[[plugins]]
repo = 'suan/vim-instant-markdown'
