# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'iceberg',
    \ 'active': {
    \   'left': [
    \     [ 'mode', 'paste' ],
    \     [ 'gitbranch', 'readonly', 'filename', 'modified' ]
    \  ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'MyFugitive',
    \ },
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }

  function! MyFugitive()
    let fugitive_head = FugitiveHead()
    return strlen(fugitive_head) ? "\ue0a0 " . fugitive_head : ''
  endfunction
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
'''

# syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# language server
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
if = 'executable("node") && executable("yarn")'
hook_source_source_post = '''
  source ~/.vim/rc/plugins/coc.rc.vim
'''

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# hook_add = '''
# set hidden
# let g:LanguageCllient_serverCommands = {
#   \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
# \ }

# augroup LanguageClient_config
# autocmd!
# autocmd User LanguageClientStarted setlocal signcolumn=yes
# autocmd User LanguageClientStopped setlocal signcolumn=auto
# augroup END

# let g:LanguageClient_autoStart = 1
# nnoremap <silent> <Space>lh :call LanguageClient_textDocument_hover()<CR>
# nnoremap <silent> <Space>ld :call LanguageClient_textDocument_definition()<CR>
# nnoremap <silent> <Space>lr :call LanguageClient_textDocument_rename()<CR>
# nnoremap <silent> <Space>lf :call LanguageClient_textDocument_formatting()<CR>
# '''

# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# hook_add = '''
#   source ~/.vim/rc/plugins/vim-lsp.rc.vim
# '''

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'

# formatter
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'

# incremental search
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

# markdown preview
[[plugins]]
repo = 'suan/vim-instant-markdown'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = [ 'fugitive://.*' ]
'''
