# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

# statusline
[[plugins]]
depends  = ['vim-fugitive', 'vim-devicons']
hook_add = '''
  let g:lightline = {
    \ 'active': {
    \   'left': [
    \     [ 'mode', 'paste' ],
    \     [ 'gitbranch', 'readonly', 'filename', 'modified' ]
    \   ],
    \   'right': [
    \     [ 'lineinfo' ],
    \     [ 'percent' ],
    \     [ 'fileformat', 'fileencoding', 'myfiletype' ],
    \     [ 'coc' ],
    \   ],
    \ },
    \ 'component_function': {
    \   'gitbranch': 'MyFugitive',
    \   'myfiletype': 'MyFileType',
    \   'coc': 'coc#status',
    \ },
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }

  function! MyFugitive()
    let fugitive_head = FugitiveHead()
    return strlen(fugitive_head) ? "\ue0a0 " . fugitive_head : ''
  endfunction

  function! MyFileType()
    return winwidth(0) > 70 ? (strlen(&filetype) ? WebDevIconsGetFileTypeSymbol() . ' ' . &filetype : 'no ft') : ''
  endfunction
'''
repo     = 'itchyny/lightline.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
hook_add = '''
  set signcolumn=yes
'''
repo     = 'airblade/vim-gitgutter'

# EditorConfig
[[plugins]]
hook_add = '''
  let g:EditorConfig_exclude_patterns = [ 'fugitive://.*' ]
'''
repo     = 'editorconfig/editorconfig-vim'

# Vim
[[plugins]]
if   = '!has("nvim")'
repo = 'roxma/nvim-yarp'

[[plugins]]
if   = '!has("nvim")'
repo = 'roxma/vim-hug-neovim-rpc'

# defx
[[plugins]]
repo = 'kristijanhusak/defx-git'

# snippets
[[plugins]]
if   = 'g:lsp_type == "vim-lsp"'
repo = 'Shougo/neosnippet-snippets'

# fzf
[[plugins]]
hook_add = '''
  nnoremap <Leader>f :<C-u>Files<CR>
  nnoremap <Leader>g :<C-u>Rg<CR>
  nnoremap <Leader>b :<C-u>Buffers<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case --hidden -- ".shellescape(<q-args>),
    \   1,
    \   fzf#vim#with_preview(),
    \   <bang>0)
'''
repo     = 'junegunn/fzf.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
