# dein_lazy.toml

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'executable("python3")'
on_cmd = 'Denite'
hook_add = '''
  nmap <silent> <Leader>df :<C-u> Denite file/rec <CR>
  nmap <silent> <Leader>dg :<C-u> Denite grep <CR>
  nmap <silent> <Leader>db :<C-u> Denite buffer <CR>
  nmap <silent> <Leader>dr :<C-u> Denite register <CR>
  nmap <silent> <Leader>dl :<C-u> Denite line <CR>
'''
hook_post_source = '''
  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>
      \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d
      \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p
      \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
      \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
      \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>
      \ denite#do_map('toggle_select').'j'
  endfunction

  let s:denite_win_width_percent = 0.85
  let s:denite_win_height_percent = 0.7

  call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
    \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
    \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
    \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) / 2),
    \ })
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
if = 'executable("python3")'
depends = [
  'vim-devicons',
  'defx-icons',
  'defx-git',
]
hook_add = '''
  nnoremap <silent> <Leader>f :<C-u> Defx <CR>
'''
hook_post_source = '''
  source $XDG_CONFIG_HOME/vim/rc/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
  let g:deol#custom_map = {
    \ 'edit': 'e',
    \ 'start_insert': 'i',
    \ 'start_insert_first': 'I',
    \ 'start_append': 'a',
    \ 'start_append_last': 'A',
    \ 'execute_line': '<CR>',
    \ 'previous_prompt': '<C-p>',
    \ 'next_prompt': '<C-n>',
    \ 'paste_prompt': '<C-y>',
    \ 'bg': '<C-z>',
    \ 'quit': 'q',
    \ }

  nnoremap <Leader>o :<C-u>Deol -split=floating<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
if = 'executable("yarn")'
on_ft = 'markdown'
build = 'cd app & yarn install'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertEnter'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <Leader>ff :<C-u>Files<CR>
  nnoremap <Leader>fg :<C-u>Rg<CR>
  nnoremap <Leader>fb :<C-u>Buffers<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case --hidden -- ".shellescape(<q-args>),
    \   1,
    \   fzf#vim#with_preview(),
    \   <bang>0)
'''
