# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

# statusline
[[plugins]]
depends  = ['vim-fugitive', 'vim-devicons']
hook_add = '''
  let g:lightline = {
    \ 'active': {
    \   'left': [
    \     [ 'mode', 'paste' ],
    \     [ 'gitbranch', 'readonly', 'filename', 'modified' ]
    \   ],
    \   'right': [
    \     [ 'lineinfo' ],
    \     [ 'percent' ],
    \     [ 'fileformat', 'fileencoding', 'myfiletype' ],
    \     [ 'coc' ],
    \   ],
    \ },
    \ 'component_function': {
    \   'gitbranch': 'MyFugitive',
    \   'myfiletype': 'MyFileType',
    \   'coc': 'coc#status',
    \ },
    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }

  function! MyFugitive()
    let fugitive_head = FugitiveHead()
    return strlen(fugitive_head) ? "\ue0a0 " . fugitive_head : ''
  endfunction

  function! MyFileType()
    return winwidth(0) > 70 ? (strlen(&filetype) ? WebDevIconsGetFileTypeSymbol() . ' ' . &filetype : 'no ft') : ''
  endfunction
'''
repo     = 'itchyny/lightline.vim'

[[plugins]]
depends  = ['vim-devicons', 'lightline-bufferline']
hook_add = '''
  let g:lightline.tabline = {
    \   'left': [
    \     [ 'buffers' ],
    \   ],
    \   'right': [
    \     [ 'close' ],
    \   ],
    \ }

  let g:lightline.component_expand = {
    \   'buffers': 'lightline#bufferline#buffers',
    \ }

  let g:lightline.component_type = {
    \   'buffers': 'tabsel',
    \ }

  let g:lightline#bufferline#enable_devicons = 1
  let g:lightline#bufferline#show_number = 1

  nmap t1 <Plug>lightline#bufferline#go(1)
  nmap t2 <Plug>lightline#bufferline#go(2)
  nmap t3 <Plug>lightline#bufferline#go(3)
  nmap t4 <Plug>lightline#bufferline#go(4)
  nmap t5 <Plug>lightline#bufferline#go(5)
  nmap t6 <Plug>lightline#bufferline#go(6)
  nmap t7 <Plug>lightline#bufferline#go(7)
  nmap t8 <Plug>lightline#bufferline#go(8)
  nmap t9 <Plug>lightline#bufferline#go(9)
  nmap t0 <Plug>lightline#bufferline#go(10)
'''
repo     = 'mengelbrecht/lightline-bufferline'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
hook_add = '''
  set signcolumn=yes
'''
repo     = 'airblade/vim-gitgutter'

# EditorConfig
[[plugins]]
hook_add = '''
  let g:EditorConfig_exclude_patterns = [ 'fugitive://.*' ]
'''
repo     = 'editorconfig/editorconfig-vim'

# Vim
[[plugins]]
if   = '!has("nvim")'
repo = 'roxma/nvim-yarp'

[[plugins]]
if   = '!has("nvim")'
repo = 'roxma/vim-hug-neovim-rpc'

# defx
[[plugins]]
repo = 'kristijanhusak/defx-git'

# snippets
[[plugins]]
if   = 'g:lsp_type == "vim-lsp"'
repo = 'Shougo/neosnippet-snippets'

# fzf
[[plugins]]
hook_add = '''
  nnoremap <Leader>f :<C-u>Files<CR>
  nnoremap <Leader>g :<C-u>Rg<CR>
  nnoremap <Leader>b :<C-u>Buffers<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case --hidden -- ".shellescape(<q-args>),
    \   1,
    \   fzf#vim#with_preview(),
    \   <bang>0)
'''
repo     = 'junegunn/fzf.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
hook_add = '''
  let g:neoterm_default_mod='belowright'
  let g:neoterm_size=10
  let g:neoterm_autoinsert = 1
  let g:neoterm_autoscroll=1
  nnoremap <silent> <C-t> :Ttoggle<CR>
  tnoremap <silent> <C-t> <C-\><C-n>:Ttoggle<CR>
'''
repo     = 'kassio/neoterm'
