# dein_lazy.toml

[[plugins]]
repo = 'Shougo/defx.nvim'
if = 'executable("python3")'
depends = [
  'vim-devicons',
  'defx-icons',
  'defx-git',
]
hook_add = '''
  nnoremap <silent> <Leader>t :<C-u> Defx <CR>
'''
hook_post_source = '''
  source $XDG_CONFIG_HOME/vim/rc/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
  let g:deol#custom_map = {
    \ 'edit': 'e',
    \ 'start_insert': 'i',
    \ 'start_insert_first': 'I',
    \ 'start_append': 'a',
    \ 'start_append_last': 'A',
    \ 'execute_line': '<CR>',
    \ 'previous_prompt': '<C-p>',
    \ 'next_prompt': '<C-n>',
    \ 'paste_prompt': '<C-y>',
    \ 'bg': '<C-z>',
    \ 'quit': 'q',
    \ }

  nnoremap <Leader>o :<C-u>Deol -split=floating<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
if = 'executable("yarn")'
on_ft = 'markdown'
build = 'cd app & yarn install'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertEnter'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap [Fzf] <Nop>
  nmap <Leader>f [Fzf]

  nnoremap [Fzf]f :<C-u>Files<CR>
  nnoremap [Fzf]g :<C-u>Rg<CR>
  nnoremap [Fzf]b :<C-u>Buffers<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   "rg --column --line-number --no-heading --color=always --smart-case --hidden -- ".shellescape(<q-args>),
    \   1,
    \   fzf#vim#with_preview(),
    \   <bang>0)
'''
