# dein_complete.toml

[[plugins]]
build       = ':UpdateRemotePlugins'
depends     = ['neosnippet.vim']
hook_add    = '''
  let g:deoplete#enable_at_startup = 1
'''
hook_source = '''
  set completeopt-=preview

  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"

  call deoplete#custom#option({
    \ 'auto_complete': v:true,
    \ 'min_pattern_length': 2,
    \ 'auto_complete_delay': 0,
    \ 'auto_refresh_delay': 20,
    \ 'refresh_always': v:true,
    \ 'smart_case': v:true,
    \ 'camel_case': v:true,
    \ })
'''
if          = 'g:lsp_type == "vim-lsp"'
on_event    = 'InsertEnter'
repo        = 'Shougo/deoplete.nvim'

[[plugins]]
depends     = ['neosnippet-snippets']
hook_source = '''
  " Plugin key-m"appings.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
if          = 'g:lsp_type == "vim-lsp"'
on_ft       = 'snippet'
repo        = 'Shougo/neosnippet.vim'
