# dein_lazy.toml

[[plugins]]
depends          = ['vim-devicons', 'defx-icons', 'defx-git']
hook_add         = '''
  nnoremap <silent> <Leader>t :<C-u> Defx <CR>
'''
hook_post_source = '''
  source $XDG_CONFIG_HOME/vim/rc/plugins/defx.rc.vim
'''
repo             = 'Shougo/defx.nvim'

[[plugins]]
hook_add = '''
  let g:deol#custom_map = {
    \ 'edit': 'e',
    \ 'start_insert': 'i',
    \ 'start_insert_first': 'I',
    \ 'start_append': 'a',
    \ 'start_append_last': 'A',
    \ 'execute_line': '<CR>',
    \ 'previous_prompt': '<C-p>',
    \ 'next_prompt': '<C-n>',
    \ 'paste_prompt': '<C-y>',
    \ 'bg': '<C-z>',
    \ 'quit': 'q',
    \ }

  nnoremap <Leader>o :<C-u>Deol -split=horizontal<CR>
'''
repo     = 'Shougo/deol.nvim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
on_event = 'CmdwinEnter'
repo     = 'markonm/traces.vim'

[[plugins]]
on_ft = 'vim'
repo  = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
build = 'cd app & yarn install'
if    = 'executable("yarn")'
on_ft = 'markdown'
repo  = 'iamcco/markdown-preview.nvim'
