# dein_lsp.toml

[[plugins]]
depends  = ['deoplete-vim-lsp', 'vim-lsp-icons']
hook_add = '''
  source $XDG_CONFIG_HOME/nvim/rc/vim-lsp.rc.vim
'''
if       = 'g:lsp_type == "vim-lsp"'
repo     = 'prabirshrestha/vim-lsp'

[[plugins]]
depends = ['deoplete.nvim']
if      = 'g:lsp_type == "vim-lsp"'
repo    = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
depends   = ['vim-lsp']
if        = 'g:lsp_type == "vim-lsp"'
on_source = ['vim-lsp']
repo      = 'mattn/vim-lsp-icons'

[[plugins]]
depends = ['vim-lsp']
if      = 'g:lsp_type == "vim-lsp"'
on_ft   = [
  'sh',
  'cs',
  'go',
  'javascript',
  'json',
  'python',
  'rust',
  'typescript',
  'vim',
  'yaml',
]
repo    = 'mattn/vim-lsp-settings'

[[plugins]]
hook_source_post = '''
  source $XDG_CONFIG_HOME/nvim/rc/coc.rc.vim
'''
if               = 'g:lsp_type == "coc"'
repo             = 'neoclide/coc.nvim'
rev              = 'release'
