# dein_lazy.toml

# filer {{
[[plugins]]
depends          = ['vim-devicons', 'defx-icons', 'defx-git']
hook_add         = '''
  nnoremap <silent> <Leader>t :<C-u> Defx <CR>
'''
hook_post_source = '''
  source $XDG_CONFIG_HOME/nvim/rc/defx.rc.vim
'''
repo             = 'Shougo/defx.nvim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
# }}

# floating terminal
[[plugins]]
hook_add = '''
  let g:deol#custom_map = {
    \ 'edit': 'e',
    \ 'start_insert': 'i',
    \ 'start_insert_first': 'I',
    \ 'start_append': 'a',
    \ 'start_append_last': 'A',
    \ 'execute_line': '<CR>',
    \ 'previous_prompt': '<C-p>',
    \ 'next_prompt': '<C-n>',
    \ 'paste_prompt': '<C-y>',
    \ 'bg': '<C-z>',
    \ 'quit': 'q',
    \ }

  nnoremap <Leader>o :<C-u>Deol -split=floating<CR>
'''
repo     = 'Shougo/deol.nvim'


# markdown preview
[[plugins]]
build = 'cd app & yarn install'
if    = 'executable("yarn")'
on_ft = 'markdown'
repo  = 'iamcco/markdown-preview.nvim'
